### ISSUE TITLE
Mozzarilla writes 01 to 0x37 when saving a file

### ISSUE THREAD

**Issue by galap-1** [MosesofEgypt/mozzarilla#40]
I know that this is really in the weeds, and I am not sure whether this is intended behavior or not, or what the purpose is, but opening and saving a tag with mozz will cause 01 to be written to the addres 0x37 in the tag file. This is a little annoying for me because I use a binary difference checker to try to determine which of my tags have been altered from stock, or to compare different versions, but the fact that this 01 is written where it is usually 00 makes it hard to tell which tags have had their meaningful content changed.

**Comment by ShellyHerself** [comment]
That's part of a bitfield that says whether or not the tag was edited my Mozz.

A binary diff isn't really a good way to figure out tag changes either sadly. Lots of tools including the stock HEK will leave in pointers that the tools used when the tag was in memory. If you open a tag in Guerrilla, and save over the old one with no edits the file will end up being marked as changed because of this.

**Comment by galap-1** [comment]
Ah I see. that's too bad. Thanks for explaining! Any recommendation for a good way to figure out changes?

**Comment by ShellyHerself** [comment]
Not currently sadly
